### ISSUE TITLE
vmlinuz generation

### ISSUE THREAD

**Issue by SolarAquarion** [xuanruiqi/rebuild-initramfs-dracut-arch-legacy#1]
vmlinuz should be generated for grub otherwise it fails.  
https://github.com/tinywrkb/pkgbuilds/blob/main/dracut-hooks-uosys/dracut-install

Although without all the omit stuff

**Comment by xuanruiqi** [comment]
I'll look into this. I have never used GRUB, so not sure what is meant by "vmlinuz should be generated".

**Comment by SolarAquarion** [comment]
vmlinuz is already in the kernel directories, but it's not copied to /boot.
