### ISSUE TITLE
sbsign??  v1.7.1-1

### ISSUE THREAD

**Issue by mlmatlock** [xuanruiqi/rebuild-initramfs-dracut-arch-legacy#2]
pacman error when upgrading a kernel:

`[ALPM-SCRIPTLET] /usr/bin/rebuild-initramfs: line 31: sbsign: command not found`

Can this be made an option, instead of being forced to add a depend (that a lot of folks probably don't need/use)?

**Comment by xuanruiqi** [comment]
This is quite strange since I only call `sbsign` if both `--key` and `--cert` are turned on (see `rebuild-initramfs` script). Let me try to replicate the issue.

**Comment by xuanruiqi** [comment]
I can't replicate this. Are you sure you didn't config key and cert path in `/etc/rebuild-initramfs.conf`?

**Comment by xuanruiqi** [comment]
Actually I think I found the bug. I'll fix and release 1.7.2 in a moment. Please tell me if you still encounter the same problem.

**Comment by inglor** [comment]
@xuanruiqi 1.7.2 seems to fix this - thanks!

**Comment by mlmatlock** [comment]
Fixed for me as well.  Thanks, @xuanruiqi!
