### ISSUE TITLE
Non-fallback image generated without -H / --hostonly argument

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [xuanruiqi/rebuild-initramfs-dracut-arch-legacy#3]
The tool generates initramfs files as expected as non-fallback and fallback versions. However, the file sizes indicate (e.g. via `du -sh /boot/init*`) that both files are in fact fallback images. In the script code I also cannot find the `-H / --hostonly` parameter being passed to dracut.

**Comment by xuanruiqi** [comment]
Sorry, this is apparently an oversight on my part. I will fix this and release the fix immediately.

**Comment by ChristophSchmidpeter** [comment]
@xuanruiqi No worries. Thank you for the nice tool btw. :)

**Comment by xuanruiqi** [comment]
I released it on GitHub two weeks ago, but forgot to bump the version on the AUR as well. Now done!
